name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run tests
        run: |
          pytest --exitfirst --disable-warnings --maxfail=1 || exit 1

  deploy:
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Update system and install dependencies
            sudo apt-get update
            sudo apt-get install -y docker.io nginx

            # Setup app directory
            APP_DIR="/home/ubuntu/app"
            if [ ! -d "$APP_DIR" ]; then
              git clone https://github.com/KyleRobins/stage-two.git $APP_DIR
            else
              cd $APP_DIR
              git pull origin main
            fi

            # Cleanup existing containers and images
            echo "Cleaning up existing containers..."
            docker stop fastapi-app || true
            docker rm fastapi-app || true
            docker rmi fastapi-app || true

            # Build and run with exact required command
            cd $APP_DIR
            echo "Building and running container..."
            docker build -t fastapi-app . && docker run -d -p 8000:8000 --name fastapi-app fastapi-app

            # Wait for container to start
            echo "Waiting for container to start..."
            sleep 10

            # Check container status
            echo "Container status:"
            docker ps -a
            echo "Container logs:"
            docker logs fastapi-app

            # Configure Nginx
            sudo bash -c 'cat > /etc/nginx/sites-available/fastapi <<EOL
            server {
                listen 80;
                server_name _;

                location / {
                    proxy_pass http://127.0.0.1:8000;
                    proxy_set_header Host \$host;
                    proxy_set_header X-Real-IP \$remote_addr;
                    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
                    proxy_set_header X-Forwarded-Proto http;
                }
            }
            EOL'

            sudo ln -sf /etc/nginx/sites-available/fastapi /etc/nginx/sites-enabled/
            sudo rm -f /etc/nginx/sites-enabled/default
            sudo nginx -t
            sudo systemctl restart nginx

            # Health check
            echo "Testing application..."
            for i in {1..12}; do
              if curl -s http://localhost:8000/healthcheck; then
                echo "Application is ready!"
                exit 0
              fi
              echo "Waiting... ($i/12)"
              sleep 5
            done

            echo "Application failed to respond. Logs:"
            docker logs fastapi-app
            echo "Nginx error log:"
            sudo tail -n 50 /var/log/nginx/error.log
            exit 1
