name: Deploy FastAPI App

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest --exitfirst --disable-warnings --maxfail=1 || exit 1

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Update system and install dependencies
            sudo apt-get update
            sudo apt-get install -y docker.io nginx

            # Setup Docker permissions
            sudo groupadd -f docker
            sudo usermod -aG docker ubuntu
            sudo chown root:docker /var/run/docker.sock
            sudo chmod 666 /var/run/docker.sock
            sudo systemctl restart docker
            newgrp docker

            # Setup app directory
            APP_DIR="/home/ubuntu/app"
            if [ ! -d "$APP_DIR" ]; then
              git clone https://github.com/KyleRobins/stage-two.git $APP_DIR
            else
              cd $APP_DIR
              git pull origin main
            fi

            # Stop and remove existing container
            docker stop fastapi-app || true
            docker rm fastapi-app || true

            # Build and run with exact required command
            cd $APP_DIR
            docker build -t fastapi-app . && docker run -d -p 8000:8000 --name fastapi-app fastapi-app

            # Configure Nginx
            sudo bash -c 'cat > /etc/nginx/sites-available/fastapi <<EOL
            server {
                listen 80;
                server_name _;

                location / {
                    proxy_pass http://localhost:8000;
                    proxy_set_header Host \$host;
                    proxy_set_header X-Real-IP \$remote_addr;
                    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
                    proxy_set_header X-Forwarded-Proto http;
                }
            }
            EOL'

            sudo ln -sf /etc/nginx/sites-available/fastapi /etc/nginx/sites-enabled/
            sudo rm -f /etc/nginx/sites-enabled/default
            sudo nginx -t
            sudo systemctl restart nginx

            # Wait for application to be ready
            echo "Waiting for application to start..."
            for i in {1..6}; do
              if curl -s http://localhost:8000/healthcheck | grep -q "active"; then
                echo "Application is ready!"
                exit 0
              fi
              echo "Attempt $i of 6"
              sleep 10
            done

            echo "Application failed to start. Logs:"
            docker logs fastapi-app
            exit 1
