name: Deploy FastAPI Application

on:
  push:
    branches: [main]

# Add concurrency control
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest || exit 1

  deploy:
    timeout-minutes: 15
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Update and setup
            sudo apt-get update
            sudo apt-get install -y ca-certificates curl gnupg nginx
            sudo install -m 0755 -d /etc/apt/keyrings
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
            sudo chmod a+r /etc/apt/keyrings/docker.gpg
            echo \
              "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
              "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
              sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
            sudo apt-get update
            sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

            # Configure Docker permissions
            sudo systemctl start docker
            sudo systemctl enable docker
            sudo groupadd -f docker
            sudo usermod -aG docker ubuntu
            sudo chmod 666 /var/run/docker.sock

            # Setup app directory with correct permissions
            if [ ! -d "/app" ]; then
              sudo git clone https://github.com/KyleRobins/stage-two.git /app
              sudo chown -R ubuntu:ubuntu /app
            else
              cd /app
              sudo git pull origin main
            fi

            # Update docker-compose.yml to remove version
            cd /app
            sed -i '/^version:/d' docker-compose.yml

            # Configure Nginx
            sudo bash -c 'cat > /etc/nginx/sites-available/fastapi <<EOL
            server {
                listen 80;
                server_name _;
                
                location / {
                    proxy_pass http://localhost:8000;
                    proxy_set_header Host \$host;
                    proxy_set_header X-Real-IP \$remote_addr;
                }
            }
            EOL'

            sudo ln -sf /etc/nginx/sites-available/fastapi /etc/nginx/sites-enabled/
            sudo rm -f /etc/nginx/sites-enabled/default
            sudo nginx -t
            sudo systemctl restart nginx

            # Deploy application with sudo
            cd /app
            sudo -E docker compose down || true
            sudo -E docker compose up --build -d

            # Wait for container to be ready
            echo "Waiting for application to be ready..."
            for i in {1..30}; do
              if curl -s http://localhost:8000/health | grep -q "healthy"; then
                echo "Application is ready!"
                exit 0
              fi
              echo "Waiting... ($i/30)"
              sleep 10
            done
            echo "Application failed to become ready in time"
            exit 1
